url: https://lailson.github.io
baseurl: /escola_de_danca/

# Site settings
title: Escola de dança Luciana Libânio 
email: contato@lucianalibanio.com.br
description: " Dançar é sonhar sem sair do chão."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff00f0
  secondary: ec70f1 
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Luciana Libânio
  pic: 1
  position: Professor de dança do ventre
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Em Breve
  pic: 2
  position: Professor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Em breve
  pic: 3
  position: Professora
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url: https://www.facebook.com/pages/Escola-de-Dan%C3%A7a-Luciana-Libanio/324640144402180?fref=ts

# Postal address (add as many lines as necessary)
address:
  - line: Rua Arlindo Nogueira, 537, Centro Norte
  - line: Teresina - Piauí

# Build settings
markdown: kramdown
permalink: pretty